#!/usr/bin/env python3
"""
Extract POS tags from Kiwi C++ source code using tree-sitter.

This script parses the Kiwi C++ header file (Types.h) to extract
POSTag enum definitions and generates a Go file with the corresponding
POS type constants.

Usage:
    python scripts/extract_postags.py [version]

Example:
    python scripts/extract_postags.py v0.23.2
"""

import sys
import urllib.request
from pathlib import Path

import tree_sitter_cpp as tscpp
from tree_sitter import Language, Parser

# Initialize parser
CPP_LANGUAGE = Language(tscpp.language())

# GitHub raw content URL template
KIWI_TYPES_H_URL = "https://raw.githubusercontent.com/bab2min/Kiwi/{version}/include/kiwi/Types.h"
KIWI_UTILS_CPP_URL = "https://raw.githubusercontent.com/bab2min/Kiwi/{version}/src/Utils.cpp"


def fetch_file(url: str) -> str:
    """Fetch file content from URL."""
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def extract_enum_values(source: str, enum_name: str) -> list[dict]:
    """Extract enum values from C++ source code using tree-sitter."""
    parser = Parser(CPP_LANGUAGE)
    tree = parser.parse(bytes(source, "utf8"))

    results = []

    def traverse(node):
        if node.type == "enum_specifier":
            # Check if this is the enum we're looking for
            name_node = node.child_by_field_name("name")
            if name_node and name_node.text.decode() == enum_name:
                # Find the body
                body = node.child_by_field_name("body")
                if body:
                    for child in body.children:
                        if child.type == "enumerator":
                            name = child.child_by_field_name("name")
                            value = child.child_by_field_name("value")
                            if name:
                                entry = {
                                    "name": name.text.decode(),
                                    "value": value.text.decode() if value else None,
                                }
                                results.append(entry)
        for child in node.children:
            traverse(child)

    traverse(tree.root_node)
    return results


def extract_tag_strings(source: str) -> list[str]:
    """Extract tag string array from Utils.cpp using regex."""
    import re

    # Find the tags array in tagToString function
    # Pattern: static const char* tags[] = { "TAG1", "TAG2", ... }
    pattern = r'static\s+const\s+char\s*\*\s*tags\s*\[\]\s*=\s*\{([^}]+)\}'
    match = re.search(pattern, source, re.DOTALL)

    if not match:
        return []

    # Extract strings from the array
    content = match.group(1)
    string_pattern = r'"([^"]+)"'
    return re.findall(string_pattern, content)


def map_cpp_to_go_tag(cpp_name: str, tag_string: str) -> tuple[str, str]:
    """Map C++ enum name to Go constant name and string value."""
    # Special cases
    special_mappings = {
        "unknown": ("POS_UNKNOWN", "UN"),
        "irregular": None,  # Skip - this is a flag, not a POS tag
        "max": None,  # Skip - this is a size marker
        "p": ("POS_P", "P"),
        "pv": ("POS_PV", "P"),  # alias for p
        "pa": ("POS_PA", "P"),  # p + 1
        "unknown_feat_ha": None,  # Skip - internal use
    }

    if cpp_name in special_mappings:
        return special_mappings[cpp_name]

    # Handle irregular variants (vvi, vai, vxi, xsai, pvi, pai)
    if cpp_name.endswith("i") and len(cpp_name) > 2:
        base = cpp_name[:-1]
        if base in ("vv", "va", "vx", "xsa", "pv", "pa"):
            go_name = f"POS_{base.upper()}_I"
            go_value = f"{base.upper()}-I"
            return (go_name, go_value)

    # Default mapping: uppercase and add POS_ prefix
    go_name = f"POS_{cpp_name.upper()}"
    go_value = tag_string if tag_string else cpp_name.upper()

    return (go_name, go_value)


def generate_go_file(tags: list[dict], tag_strings: list[str], version: str) -> str:
    """Generate Go source file with POS type definitions."""
    # Build tag string lookup
    string_lookup = {}
    for i, s in enumerate(tag_strings):
        string_lookup[i] = s

    lines = []
    lines.append("// Code generated by scripts/extract_postags.py; DO NOT EDIT.")
    lines.append(f"// Source: Kiwi {version}")
    lines.append("//")
    lines.append("// To regenerate, run: make sync-postypes")
    lines.append("")
    lines.append("package kiwi")
    lines.append("")
    lines.append('import "fmt"')
    lines.append("")
    lines.append("type POSType string")
    lines.append("")
    lines.append("const (")

    # Track which tags we've added and collect for alignment
    added_tags = set()
    tag_entries = []

    for i, tag in enumerate(tags):
        cpp_name = tag["name"]
        tag_string = string_lookup.get(i, cpp_name.upper())

        result = map_cpp_to_go_tag(cpp_name, tag_string)
        if result is None:
            continue

        go_name, go_value = result
        if go_name in added_tags:
            continue

        added_tags.add(go_name)
        tag_entries.append((go_name, go_value))

    # Calculate max name length for alignment
    max_name_len = max(len(name) for name, _ in tag_entries)

    # Generate aligned output
    for go_name, go_value in tag_entries:
        padding = " " * (max_name_len - len(go_name) + 1)
        lines.append(f'\t{go_name}{padding}POSType = "{go_value}"')

    lines.append(")")
    lines.append("")

    # Generate isValid function
    lines.append("func (p POSType) isValid() bool {")
    lines.append("\tswitch p {")
    lines.append("\tcase")

    valid_tags = []
    for tag in tags:
        cpp_name = tag["name"]
        result = map_cpp_to_go_tag(cpp_name, "")
        if result is None:
            continue
        go_name = result[0]
        if go_name not in added_tags:
            continue
        valid_tags.append(go_name)

    lines.append(",\n".join(f"\t\t{tag}" for tag in valid_tags) + ":")
    lines.append("\t\treturn true")
    lines.append("\tdefault:")
    lines.append("\t\treturn false")
    lines.append("\t}")
    lines.append("}")
    lines.append("")

    # Generate ParsePOSType function
    lines.append("// ParsePOSType return POS Tag for result")
    lines.append("func ParsePOSType(t string) (POSType, error) {")
    lines.append("\tpos := POSType(t)")
    lines.append("\tif !pos.isValid() {")
    lines.append('\t\treturn POS_UNKNOWN, fmt.Errorf("POS type parse err. input type: %s", t)')
    lines.append("\t}")
    lines.append("\treturn pos, nil")
    lines.append("}")

    return "\n".join(lines)


def main():
    version = sys.argv[1] if len(sys.argv) > 1 else "v0.23.2"

    print(f"Extracting POS tags from Kiwi {version}...")

    # Fetch source files
    types_url = KIWI_TYPES_H_URL.format(version=version)
    utils_url = KIWI_UTILS_CPP_URL.format(version=version)

    print(f"Fetching {types_url}")
    types_source = fetch_file(types_url)

    print(f"Fetching {utils_url}")
    utils_source = fetch_file(utils_url)

    # Extract enum values
    print("Parsing POSTag enum...")
    tags = extract_enum_values(types_source, "POSTag")
    print(f"Found {len(tags)} enum values")

    # Extract tag strings
    print("Parsing tag strings...")
    tag_strings = extract_tag_strings(utils_source)
    print(f"Found {len(tag_strings)} tag strings")

    # Generate Go file
    go_content = generate_go_file(tags, tag_strings, version)

    # Write output
    output_path = Path("postype_generated.go")
    output_path.write_text(go_content)
    print(f"Generated {output_path}")

    # Print summary
    print("\nExtracted tags:")
    for i, tag in enumerate(tags):
        tag_str = tag_strings[i] if i < len(tag_strings) else "?"
        result = map_cpp_to_go_tag(tag["name"], tag_str)
        if result:
            print(f"  {tag['name']:20s} -> {result[0]:20s} = \"{result[1]}\"")
        else:
            print(f"  {tag['name']:20s} -> (skipped)")


if __name__ == "__main__":
    main()
