on:
  push:
    branches:
      - main
  pull_request:
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - '1.23'
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - run: make install-kiwi
      - run: make test

