on:
  push:
    branches:
      - main
  pull_request:
name: CI
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - run: make install-kiwi
      - run: make test
